### ISSUE TITLE
Problem to export…

### ISSUE THREAD

**Issue by Ceffsn** [AndreasSko/ios-jwlm#36]
Hey great and wonderful program!
Though now i can’t make any new merges for my JW Library…
![95BFBBD6-AD81-42EC-9614-698976C8510C](https://user-images.githubusercontent.com/88610419/130348305-d86eb534-c956-46ad-bf70-1fdcdaafad25.png)

What can i do? My English is not the best… 
Dear Brother Cevin Strümpfel 
Aus Deutschland :)

**Comment by AndreasSko** [comment]
Hey Cevin, 
thank you for your report!
This looks like the same issue described in https://github.com/AndreasSko/go-jwlm/issues/97 and documented with https://github.com/AndreasSko/go-jwlm/issues/105. 
In summary: The issue happens when one backup has migrated to the Study Edition of the revised New World Translation, while the other backup has its markings still in the regular version. I'm working on solving this problem. As a workaround, it would be possible to simply remove all markings in the backup that still uses the non-study edition. Merging it should recover those again - this time in the Study Edition. If you haven't used the Study Edition on the backup at all, it might even be possible to trigger the migration manually by downloading the Study Edition on that device again - though this is just an assumption, I haven't really tested it..

Summary in German:
Das ist leider ein bekanntes Problem. Es tritt dann auf, wenn du in einem Backup bereits deine Markierung auf die Studienausgabe migriert hast (vielleicht erinnerst du dich noch daran, dass das JW Library beim ersten Download angeboten hat), während das andere Backup die Markierungen noch in der normalen Ausgabe hat - dadurch entstehen dann Konflikte, die JWLM nicht erkennen kann. Ich arbeite aktuell an einem Fix, weiß aber nicht, wie lange ich dafür brauche..
Als "Workaround" könntest du versuchen, alle Markierungen in dem Backup zu löschen, das noch die normale Bibel nutzt - nachdem du dann beide Backups gemergt hast, sollten sie wiederhergestellt sein. Eine andere Idee wär, auf dem Gerät, das noch die normale Ausgabe nutzt, die Studienausgabe herunterzuladen um dadurch zu versuchen, die Migration manuell zu starten - aber das ist nur eine Idee, hab es selbst nicht getestet..

**Comment by Ceffsn** [comment]
Hello Andreas?
Thanks for the message. 
I am trying to see and understand the other problem, thank you for pointing out my "problem".
But I really use only the Study bible now. Both devices use usually only the German study bible “Studienbibel”.
From time to time i use English or Spanish Bibels but without markings there…
That should not be a problem ? 
Greetings!

**Comment by AndreasSko** [comment]
Could you check if there are maybe some markings left in the non-study edition in one of those backups? And if so, does that marking still exists in the other backup as well, or do you only find that marking in the study edition then? If the latter is the case, that would be the issue. 
But I will try to work on that fix in the next few days. Hopefully, I'm then able to publish a beta version on Testflight, which you could try :slightly_smiling_face:

**Comment by Ceffsn** [comment]
Just for better understanding.
I should check if I have markings in other Bibles besides the study version?
That's a lot of books in total ...
Is there perhaps a shorter way to see this?

**Comment by AndreasSko** [comment]
That's great to hear, thank you for the feedback! 😊
I will polish the fix a bit and it hopefully arrives in the App Store within the next 1-2 weeks. Feel free to use the TestFlight beta until then 🙂

**Comment by Ceffsn** [comment]
Thanks a lot 🙏🏼
I’m looking forward for your update in the AppStore 😁
