### ISSUE TITLE
JWLM is not available for Ukrainian AppStore

### ISSUE THREAD

**Issue by ZeroBit** [AndreasSko/ios-jwlm#50]
Hello, I cannot find JWLM in the AppStore for Ukraine. Is it possible to fix it?
Thank you for the wonderful app!!!

**Comment by AndreasSko** [comment]
Thanks for your message! I had to temporarily remove the app completely because its name might confuse some into thinking the app is distributed by the organization. Today I published it again with a slightly different name ("Library Merger"). So hopefully you are able to download it within the next few hours :)

**Comment by AndreasSko** [comment]
Closed by #49
